import { Editor } from '@tiptap/core';
export declare class CommandManager {
    private editor;
    constructor(editor: Editor);
    /**
     * Executes a command with focused state.
     */
    execute(fn: (chain: any) => any): any;
    bold: () => any;
    italic: () => any;
    underline: () => any;
    strike: () => any;
    subscript: () => any;
    superscript: () => any;
    code: () => any;
    fontFamily: (font: string) => any;
    fontSize: (size: string) => any;
    setColor: (color: string) => any;
    setHighlight: (color: string) => any;
    transform: (type: string) => any;
    toggleSmallCaps: () => any;
    letterSpacing: (spacing: string) => any;
    wordSpacing: (spacing: string) => any;
    align: (alignment: any) => any;
    lineHeight: (height: string) => any;
    spacing: (top: string, bottom: string) => any;
    paragraphLayout: (attrs: any) => any;
    indent: () => any;
    outdent: () => any;
    heading: (level: any) => any;
    paragraph: () => any;
    blockquote: () => any;
    codeBlock: () => any;
    horizontalRule: () => any;
    bulletList: () => any;
    orderedList: () => any;
    taskList: () => any;
    setListStyle: (style: string) => any;
    setListStartNumber: (n: number) => any;
    insertTable: (options: any) => any;
    addColumnBefore: () => any;
    addColumnAfter: () => any;
    deleteColumn: () => any;
    addRowBefore: () => any;
    addRowAfter: () => any;
    deleteRow: () => any;
    deleteTable: () => any;
    mergeCells: () => any;
    splitCell: () => any;
    toggleHeaderColumn: () => any;
    toggleHeaderRow: () => any;
    toggleHeaderCell: () => any;
    mergeOrSplit: () => any;
    setTableCellAttribute: (name: string, value: any) => any;
    setTableStyle: (style: string) => any;
    insertImage: (src: string) => any;
    setImageSize: (width: string, height?: string) => any;
    setImageFloat: (float: "left" | "right" | "none") => any;
    insertCaption: (type?: string) => any;
    insertMathInline: (latex: string) => any;
    insertMathBlock: (latex: string) => any;
    pageBreak: () => any;
    footnote: () => any;
    sectionBreak: () => any;
    pageLayout: (options: any) => any;
    applyStyle: (name: string) => any;
    updateStyle: (name: string, attrs: any) => any;
    insertTableOfContents: () => any;
    insertCitation: (key: string, label?: string) => any;
    insertBibliography: () => any;
    executeSlashCommand: (title: string) => any;
    clearFormatting: () => any;
    undo: () => any;
    redo: () => any;
    selectAll: () => any;
    exportDocx: () => any;
    printDoc: () => void;
}
